name: Build Android APK (Manual)

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Use a stable Python version

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-venv autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

    - name: Create and activate virtual environment
      run: |
        python3 -m venv .build-venv
        source .build-venv/bin/activate
        pip install buildozer cython setuptools sh

    - name: Build the APK
      run: |
        source .build-venv/bin/activate
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        # Buildozer places the APK in the bin/ directory
        path: bin/*.apk