name: Build Android APK

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug

    - name: Upload APK
      # THIS IS THE CORRECTED LINE:
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}